### ISSUE TITLE
py3k compatibility

### ISSUE THREAD

**Issue by lmjohns3** [samfoo/vt102#5]
PR #4 updates the code so that the syntax is py3k compatible; however, the code still doesn't function properly in py3k because of the transition to the explicit ``bytes`` type. In principle it should be possible to update the code to use bytes everywhere (instead of the weirdly ambiguous ``str``), but it might take a bit of work?

**Comment by samfoo** [comment]
I don't think transitioning to a bytes type makes sense for the API. I've made it so that bytes are used internally, but strings are still passed to the API. Should work now, I'll release a new version to pypy today. Thanks for the effort!

**Comment by lmjohns3** [comment]
Ok, sounds great, thanks!

**Comment by samfoo** [comment]
[Done!](https://pypi.python.org/pypi?:action=display&name=vt102&version=0.4)
